server:
  port: 8804
spring:
  boot:
    admin:
      client:
        url: http://admin-server:8804
  application:
    name: admin-server
  zipkin:
    base-url: http://zipkin-server:8803
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8801/eureka
