version: "3.9"
services:
  admin-server:
    build: ./admin-server
    image: admin-server
    container_name: admin-server
    stdin_open: true
    tty: true
    depends_on:
      - eureka-server
      - zipkin-server
  eureka-server:
    build: ./eureka-server
    image: eureka-server
    container_name: eureka-server
    stdin_open: true
    tty: true
  feign-consumer:
    build: ./feign-consumer
    image: feign-consumer
    container_name: feign-consumer
    stdin_open: true
    tty: true
    depends_on:
      - eureka-server
      - zipkin-server
      - admin-server
  feign-provider:
    build: ./feign-provider
    image: feign-provider
    container_name: feign-provider
    stdin_open: true
    tty: true
    depends_on:
      - eureka-server
      - zipkin-server
      - admin-server
  hystrix-server:
    build: ./hystrix-server
    image: hystrix-provider
    container_name: hystrix-provider
    stdin_open: true
    tty: true
    depends_on:
      - eureka-server
      - zipkin-server
      - admin-server
  turbine-server:
    build: ./turbine-server
    image: turbine-server
    container_name: turbine-server
    stdin_open: true
    tty: true
    depends_on:
      - eureka-server
      - zipkin-server
      - admin-server
  zipkin-server:
    build: ./zipkin-server
    image: zipkin-server
    container_name: zipkin-server
    stdin_open: true
    tty: true
    depends_on:
      - eureka-server
  zuul-server:
    build: ./zuul-server
    image: zuul-server
    container_name: zuul-server
    stdin_open: true
    tty: true
    ports:
    - 8080:8805
    depends_on:
      - admin-server
      - eureka-server
      - feign-consumer
      - feign-provider
      - hystrix-server
      - turbine-server
      - zipkin-server
