version: "3.9"
services:
  admin-server:
    build: ./admin-server
    image: admin-server
    container_name: admin-server
    stdin_open: true
    tty: true
    ports:
    - 8804:8804
    command: ["./check_eureka.sh", "admin-server-1.0-SNAPSHOT"]
    depends_on:
      - eureka-server
      - zipkin-server
    healthcheck:
      test: "/bin/netstat -anpt|grep 8804"
      retries: 1
      timeout: 3s
      interval: 30s
  eureka-server:
    build: ./eureka-server
    image: eureka-server
    container_name: eureka-server
    stdin_open: true
    tty: true
    ports:
    - 8801:8801
    command: ["java", "-jar", "eureka-server-1.0-SNAPSHOT.jar"]
    healthcheck:
      test: "/bin/netstat -anpt|grep 8801"
      retries: 1
      timeout: 3s
      interval: 30s
  feign-consumer:
    build: ./feign-consumer
    image: feign-consumer
    container_name: feign-consumer
    stdin_open: true
    tty: true
    ports:
    - 8081:8081
    command: ["./check_eureka.sh", "feign-consumer-1.0-SNAPSHOT"]
    depends_on:
      - eureka-server
      - zipkin-server
      - admin-server
    healthcheck:
      test: "/bin/netstat -anpt|grep 8081"
      retries: 1
      timeout: 3s
      interval: 30s
  feign-provider:
    build: ./feign-provider
    image: feign-provider
    container_name: feign-provider
    stdin_open: true
    tty: true
    ports:
    - 8083:8083
    command: ["./check_eureka.sh", "feign-provider-1.0-SNAPSHOT"]
    depends_on:
      - eureka-server
      - zipkin-server
      - admin-server
    healthcheck:
      test: "/bin/netstat -anpt|grep 8083"
      retries: 1
      timeout: 3s
      interval: 30s
  hystrix-server:
    build: ./hystrix-server
    image: hystrix-provider
    container_name: hystrix-provider
    stdin_open: true
    tty: true
    ports:
    - 8806:8806
    command: ["./check_eureka.sh", "hystrix-server-1.0-SNAPSHOT"]
    depends_on:
      - eureka-server
      - zipkin-server
      - admin-server
    healthcheck:
      test: "/bin/netstat -anpt|grep 8806"
      retries: 1
      timeout: 3s
      interval: 30s
  turbine-server:
    build: ./turbine-server
    image: turbine-server
    container_name: turbine-server
    stdin_open: true
    tty: true
    ports:
      - 8807:8807
    command: ["./check_eureka.sh", "turbine-server-1.0-SNAPSHOT"]
    depends_on:
      - eureka-server
      - zipkin-server
      - admin-server
    healthcheck:
      test: "/bin/netstat -anpt|grep 8807"
      retries: 1
      timeout: 3s
      interval: 30s
  zipkin-server:
    build: ./zipkin-server
    image: zipkin-server
    container_name: zipkin-server
    stdin_open: true
    tty: true
    ports:
    - 8803:8803
    command: ["./check_eureka.sh", "zipkin-server-1.0-SNAPSHOT"]
    depends_on:
      - eureka-server
    healthcheck:
      test: "/bin/netstat -anpt|grep 8803"
      retries: 1
      timeout: 3s
      interval: 30s
  zuul-server:
    build: ./zuul-server
    image: zuul-server
    container_name: zuul-server
    stdin_open: true
    tty: true
    ports:
    - 8080:8805
    command: ["./check_eureka.sh", "zuul-server-1.0-SNAPSHOT"]
    depends_on:
      - admin-server
      - eureka-server
      - feign-consumer
      - feign-provider
      - hystrix-server
      - turbine-server
      - zipkin-server
    healthcheck:
      test: "/bin/netstat -anpt|grep 8805"
      retries: 1
      timeout: 3s
      interval: 30s
