server:
  port: 8805
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  routes:
    provider:
      path: /provider/**
      serviceId: feign-provider
    consumer:
      path: /consumer/**
      serviceId: feign-consumer
spring:
  application:
    name: zuul-server
  boot:
    admin:
      client:
        url: http://admin-server:8804
  zipkin:
    base-url: http://zipkin-server:8803
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8801/eureka
