server:
  port: 8801
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8802/eureka
spring:
  application:
    name: eureka-server