server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8801/eureka
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: feign-consumer
  boot:
    admin:
      client:
        url: http://admin-server:8804
  zipkin:
    base-url: http://zipkin-server:8803
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.shun: debug

---
# consumer1
spring:
  profiles: consumer1
  application:
    name: consumer1
server:
  port: 8801

---
spring:
  profiles: consumer2
  application:
    name: consumer2
# consumer1
server:
  port: 8802

