server:
  port: 8806
spring:
  boot:
    admin:
      client:
        url: http://admin-server:8804
  zipkin:
    base-url: http://admin-server:8803
  application:
    name: hystrix-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8801/eureka
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
