server:
  port: 8803
spring:
  application:
    name: zipkin-server
  boot:
    admin:
      client:
        url: http://localhost:8804
  zipkin:
    base-url: http://localhost:8803
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka,http://localhost:8802/eureka
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: '*'
