server:
  port: 8807
spring:
  application:
    name: turbine-server
  boot:
    admin:
      client:
        url: http://localhost:8804
  zipkin:
    base-url: http://localhost:8803
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka,http://localhost:8802/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
turbine:
  cluster-name-expression: new String('default')
  app-config: feign-consumer,feign-consumer-2
  combine-host-port: true