server:
  port: 8807
spring:
  application:
    name: turbine-server
  boot:
    admin:
      client:
        url: http://admin-server:8804
  zipkin:
    base-url: http://zipkin-server:8803
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8801/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
turbine:
  cluster-name-expression: new String('default')
  app-config: feign-consumer
  combine-host-port: true