server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka,http://localhost:8802/eureka
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: feign-provider
  boot:
    admin:
      client:
        url: http://localhost:8804
  zipkin:
    base-url: http://localhost:8803
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  hystrix:
    enabled: true
logging:
  level:
    com.shun: debug
